services:
  tf:
    build:
      context: ./containers/tf
      dockerfile: ./Dockerfile
      args:
        USERNAME: ${USER_NAME}
        USER_UID: ${USER_ID}
        WORKING_DIRECTORY: /home/${USER_NAME}/dev/

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    ports:
      - 8889:8888 # jupyter
      - 6007:6006 #tensorboard

    volumes:
      - .:/home/${USER_NAME}/dev:cache

    working_dir: /home/${USER_NAME}/dev/

  tfmarco:
    build:
      context: ./containers/tfmarco
      dockerfile: ./Dockerfile
      args:
        USERNAME: ${USER_NAME}
        USER_UID: ${USER_ID}
        WORKING_DIRECTORY: /home/${USER_NAME}/dev/

    ports:
      - 8890:8888 # jupyter
      - 6008:6006 #tensorboard

    volumes:
      - .:/home/${USER_NAME}/dev:cache

    working_dir: /home/${USER_NAME}/dev/

  xgboost:
    build:
      context: ./containers/xgboost
      dockerfile: ./Dockerfile
      args:
        USERNAME: ${USER_NAME}
        USER_UID: ${USER_ID}
        WORKING_DIRECTORY: /home/${USER_NAME}/dev/

    volumes:
      - .:/home/${USER_NAME}/dev:cache

    working_dir: /home/${USER_NAME}/dev/
    tty: true


  api_dev:
    build:
      context: ./containers/api_dev
      dockerfile: ./Dockerfile
      args:
        USERNAME: ${USER_NAME}
        USER_UID: ${USER_ID}
        WORKING_DIRECTORY: /home/${USER_NAME}/dev/
        PORT: 80

    ports:
      - 8081:80

    volumes:
      - .:/home/${USER_NAME}/dev:cache

    working_dir: /home/${USER_NAME}/dev/
    tty: true

  api_prod:
    build:
      context: ./
      dockerfile: ./containers/api_prod/Dockerfile
      args:
        USERNAME: appuser
        USER_UID: 1001
        WORKING_DIRECTORY: /app
        PORT: 80
    command: sleep infinity

    ports:
      - 8082:80