services:
  tf:
    build:
      context: ./containers/tf
      dockerfile: ./Dockerfile
      args:
        USERNAME: ${USER_NAME}
        USER_UID: ${USER_ID}
        WORKING_DIRECTORY: /home/${USER_NAME}/dev/

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    ports:
      - 8889:888 # jupyter
      - 6007:6006 #tensorboard

    volumes:
      - .:/home/${USER_NAME}/dev:cache

    working_dir: /home/${USER_NAME}/dev/

  tfmarco:
    build:
      context: ./containers/tfmarco
      dockerfile: ./Dockerfile
      args:
        USERNAME: ${USER_NAME}
        USER_UID: ${USER_ID}
        WORKING_DIRECTORY: /home/${USER_NAME}/dev/

    ports:
      - 8888:8888 # jupyter
      - 6006:6006 #tensorboard

    volumes:
      - .:/home/${USER_NAME}/dev:cache

    working_dir: /home/${USER_NAME}/dev/

  xgboost:
    build:
      context: ./containers/xgboost
      dockerfile: ./Dockerfile
      args:
        USERNAME: ${USER_NAME}
        USER_UID: ${USER_ID}
        WORKING_DIRECTORY: /home/${USER_NAME}/dev/

    volumes:
      - .:/home/${USER_NAME}/dev:cache

    working_dir: /home/${USER_NAME}/dev/
    tty: true


  api_dev:
    build:
      context: ./containers/api_dev
      dockerfile: ./Dockerfile
      args:
        USERNAME: ${USER_NAME}
        USER_UID: ${USER_ID}
        WORKING_DIRECTORY: /home/${USER_NAME}/dev/
        INTERNAL_PORT: 8999

    ports:
      - 8999:8999

    volumes:
      - .:/home/${USER_NAME}/dev:cache

    working_dir: /home/${USER_NAME}/dev/
    tty: true

  api_prod:
    build:
      context: ./containers/api_prod
      dockerfile: ./Dockerfile
      args:
        USERNAME: appuser
        USER_UID: 1001
        WORKING_DIRECTORY: /app

    ports:
      - 8998:8080