services:
  tf:
    build:
      context: ./containers/tf
      dockerfile: ./Dockerfile
      args:
        USERNAME: ${USER_NAME}
        USER_UID: ${USER_ID}
        WORKING_DIRECTORY: /home/${USER_NAME}/dev/

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    environment:
      - PATH=$${HOME}/.local/bin:$PATH

    # ports:
    #   - 8888:8888 # jupyter
    #   - 6006:6006 #tensorboard

    volumes:
      - .:/home/${USER_NAME}/dev:cache

    working_dir: /home/${USER_NAME}/dev/

  xgboost:
    build:
      context: ./containers/xgboost
      dockerfile: ./Dockerfile
      args:
        USERNAME: ${USER_NAME}
        USER_UID: ${USER_ID}
        WORKING_DIRECTORY: /home/${USER_NAME}/dev/

    # # might be able to use gpu later 
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]

    environment:
      - PATH=$${HOME}/.local/bin:$PATH

    volumes:
      - .:/home/${USER_NAME}/dev:cache

    working_dir: /home/${USER_NAME}/dev/
    tty: true


  api:
    build:
      context: ./containers/api
      dockerfile: ./Dockerfile
      args:
        USERNAME: ${USER_NAME}
        USER_UID: ${USER_ID}
        WORKING_DIRECTORY: /home/${USER_NAME}/dev/

    environment:
      - PATH=$${HOME}/.local/bin:$PATH

    volumes:
      - .:/home/${USER_NAME}/dev:cache

    working_dir: /home/${USER_NAME}/dev/
    tty: true